### ISSUE TITLE
Modbus over serial

### ISSUE THREAD

**Issue by iurly** [biancode/node-red-contrib-modbus#1]
Hi,
I understand node-red-contrib-modbus only supports modbus over TCP.
I need to deploy an application where connections are performed over a serial line.
I believe jsmodbus already supports serial connections, so the only missing part would be to add the node-red wrapper for it.
Is such a feature planned at all? If I were to implement this myself, would this be a welcome feature?
Any suggestions on how to proceed?
Thank you!

**Comment by biancode** [comment]
There were no more time to develop that feature and nobody asked for it until now. I'll start to develop that.

**Comment by iurly** [comment]
Hi,
I'm willing to contribute and I just started playing with it, though I am a newbie as far as github, node.js and node-RED are concerned.
Is there a quick way to get your feedback (in a gerrit-like workflow) without causing even more burden on your part?
Pushing draft changes to a forked github repo and issuing a pull request sounds a bit like overkill to me (especially at this stage where I'm not quite sure what I'm doing and it's very likely there's something wrong or missing...).
Thank you!

**Comment by biancode** [comment]
Hi, the best way is to fork this repo, develop your part, and send a pull request to my repo from your forked repo. I'll do the review of your code and some tests and then we'll release if it works ;)

start here: http://nodered.org/docs/creating-nodes/

**Comment by iurly** [comment]
Done! See pull request #2 . 
I guess I should've mentioned the issue in the commit message.
Feel free to shoot if there's something obviously wrong (no need to be polite...). :-)

**Comment by biancode** [comment]
please pull again and test ...

**Comment by biancode** [comment]
working well on a serial modbus software server

**Comment by biancode** [comment]
see v0.6.0 and above
