### ISSUE TITLE
Feature request: Failover IP address for Modbus TCP

### ISSUE THREAD

**Issue by sirockin** [biancode/node-red-contrib-modbus#10]
We currently use PLCs which offer redundant network capability (act as a slave on two seperate IP addresses). To make use of this, we'd like the server node to offer the option of a failover host ip and port. The server would then switch between the two when the current IP fails.

We'll be happy to attempt an implementation and submit a pull request once we have #6 sorted out.

**Comment by biancode** [comment]
sounds interesting

**Comment by biancode** [comment]
please reopen with your pull request later
