### ISSUE TITLE
Modbus read

### ISSUE THREAD

**Issue by Somavaram** [biancode/node-red-contrib-modbus#100]
Hi @biancode ,

I am presently working on Siemens S7-1500 PLC. I configured the PLC as modbus client. Now, I am trying to read the holding registers using Modbus read. But unfortunately, I am unable to establish the connection, The status on the node shows "Initialize", changes to "Error FSM not ready to read at state INIT" and then reconnecting. I have no clue how to solve this issue please help.

I have also tried using node S7 node to connect the PLC but as soon as I enter the IP address and deploy it the status on the node changes to disconnect.

Please give your valuable suggestions.

Regards,
Somavaram

**Comment by biancode** [comment]
Hi Somavaram,

did you see issue #93 or does it help to give some delay before reading?

Regards,
Klaus

**Comment by Somavaram** [comment]
Hi @biancode ,

I have tried both ways but couldn't succeed and yes there is only one node trying to establish the connection to the plc(Modbus read).

**Comment by biancode** [comment]
can you sen a picture of your configuration nodes --->  Node-RED menu -> configuration -> all  from the right upper corner, please

**Comment by Somavaram** [comment]
![error](https://user-images.githubusercontent.com/30116047/42622901-c5f09a64-85c1-11e8-8bff-8aa6126ec52a.JPG)
I see nothing like config

**Comment by biancode** [comment]
right upper corner  --- the three white lines is the Node-RED menu button ;) ---  
Node-RED menu -> Configuration nodes

**Comment by biancode** [comment]
Looks good. OK, and now the settings of the modbus-client node, please!

**Comment by biancode** [comment]
and the settings of your read node, please

**Comment by Somavaram** [comment]
![102](https://user-images.githubusercontent.com/30116047/42628552-c3342228-85d0-11e8-84ca-9af52f11e1c5.JPG)
![103](https://user-images.githubusercontent.com/30116047/42628553-c3520374-85d0-11e8-946f-217553b6ad8a.JPG)

**Comment by biancode** [comment]
all OK - now I need detailed [DEBUG logs](https://github.com/biancode/node-red-contrib-modbus/wiki/DEBUG) - you could send them via E-Mail

**Comment by biancode** [comment]
closed until we get more information

**Comment by Somavaram** [comment]
@biancode ,
 Sorry for the late reply, How do I get these debug logs or where do i find it.

**Comment by Somavaram** [comment]
I see no error in the debug(NR page) as well as command prompt.

**Comment by biancode** [comment]
[DEBUG logs](https://github.com/biancode/node-red-contrib-modbus/wiki/DEBUG)

**Comment by biancode** [comment]
we have youtube, wiki and the Node-RED Slack channel, please use it
