### ISSUE TITLE
Feature request: server mode for solving CGNAT issues on GPRS IoT devices

### ISSUE THREAD

**Issue by mainakae** [biancode/node-red-contrib-modbus#104]
**I'm submitting a ...**  (check one with "x")

 ## Feature
 - (X) feature request
 
I'm currently working on a IoT project involving ModBus TCP communications with remote low power devices connected via GPRS. Those devices are in a CGNAT (Carrier Grade NAT) network, which means that the assigned IP of the device is not accessible from the internet. The only solution (and the one we've previously used and is more or less the standard solution in related forums) we have come up with, is to start the communications from the device (as if it were a client interrogating our central server) and then re-use that channel from the server to interrogate the device.

It's doable from regular code, and (I think) a common enough problem to be considered a nice feature to have in this project.

The main caveats are:
- non standard solution (albeit commonly used)
- keeping alive the connection: forces us to send regular "heartbeats" via exceptions (whose codes may even be used to notify changes in the device, and thus trigger an update from the service)
 
In case you are interested in adding this functionality to the project, I can devote some of my time to do so (If, again, you are so inclined too) and publish it via pull-request.

Thanks for your time and for such a great node-red module!!
Pedro.

**Comment by biancode** [comment]
Hi Pedro,

you're welcome to send your pull request.
please read the [contributing.md](https://github.com/biancode/node-red-contrib-modbus/blob/master/.github/CONTRIBUTING.md)

**Comment by biancode** [comment]
please, try to write tests for the new code ...

**Comment by biancode** [comment]
please, work on branch develop - many changes are there - to fit into later releases

**Comment by biancode** [comment]
reopen with your pull request
