### ISSUE TITLE
Problem with installation contrib-modbus on RPI3

### ISSUE THREAD

**Issue by chodki** [biancode/node-red-contrib-modbus#11]
Hello,
I need help with installation node-red-contrib-modbus, on raspberry pi3
I do everything according to the instructions but in the dashboard I can't see elements modbus.

Here the installation process:
![install](https://cloud.githubusercontent.com/assets/25514289/22565618/1494ab50-e989-11e6-868d-635b3f057440.png)

After this, when I start node-red i see error in loading modbus module:
![error](https://cloud.githubusercontent.com/assets/25514289/22565667/325e78c8-e989-11e6-82a5-592c057c82aa.png)

Node-red is is up to date, on raspberry I use:
RASPBIAN JESSIE WITH PIXEL
Version:January 2017
Release date:2017-01-11
Kernel version:4.4 

Will someone tell me what' s going on?!

Thx Ł.

**Comment by biancode** [comment]
see [Wiki](https://github.com/biancode/node-red-contrib-modbus/wiki/Raspberry-PI2-and-PI3-hints) - you node version should be wrong - please test with node -v

**Comment by chodki** [comment]
Oh my God....
I didn't notice topic about pi in wiki :))
Sorry!
Now everything works perfectly, 
Goodwork Klaus!!
THX!

**Comment by biancode** [comment]
cool - have fun!
