### ISSUE TITLE
TypeError: Cannot read property 'getHolding' of null

### ISSUE THREAD

**Issue by ajinkyapuar** [biancode/node-red-contrib-modbus#110]
**I'm submitting a Problem** 

 - ( x ) unexpected behavior => please visit the Wiki before
 
 **Current behavior**
 

{"message":"TypeError: Cannot read property 'getHolding' of null","source":{"id":"96ca2d57.1abac","type":"modbus-server","name":"","count":1},"stack":"TypeError: Cannot read property 'getHolding' of null\n    at null.<anonymous> (/home/wwwroot/.node-red/node_modules/node-red-contrib-modbus/modbus/maps/modbus-server.js:131:40)\n    at emitOne (events.js:77:13)\n    at null.emit (events.js:169:7)\n    at null.Node.receive (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:215:14)\n    at InjectNode.Node.send (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:137:22)\n    at InjectNode.<anonymous> (/usr/local/lib/node_modules/node-red/nodes/core/core/20-inject.js:77:22)\n    at emitOne (events.js:77:13)\n    at InjectNode.emit (events.js:169:7)\n    at InjectNode.Node.receive (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:215:14)\n    at /usr/local/lib/node_modules/node-red/nodes/core/core/20-inject.js:105:22\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/local/lib/node_modules/node-red/node_modules/express/li..."}

 
 **Minimal reproduction of the problem with instructions**
 
   1. After deploying the project on server using one of the example flows gives the above error. 
  2. Fixed issue with node version & npm version.
  3. Node-Red manage palette has disappeared.
   
### Your Environment
**Please tell us about your environment:**

  * Device :
    
    - ( ) macOS: v 
    - ( x ) Linux: v 16.04
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
     
    
* **node-red-contrib-modbus version:** `3.6.1`

* **Node:** (min. 6.x)
   `node --version` = v8.11.4

**Comment by biancode** [comment]
It is a major version. Please, check your flows and maybe you have to update or replace some nodes like the new server. Node-RED did not update all changes automatically.

**Comment by biancode** [comment]
Oh I see, you talking about v3.6.1

**Comment by ajinkyapuar** [comment]
I've downgraded node version to v4.2.6 since there were a lot of breaking changes. could you help me fix this issue?

**Comment by ajinkyapuar** [comment]
Fixed by updating node to v6.14.4

`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - `
`sudo apt-get install -y nodejs`

**Comment by biancode** [comment]
Yes, v6 is minimum ;)

**Comment by biancode** [comment]
I'm using nvm. With that you could test with different version or you could run different nodejs instances in parallel.
