### ISSUE TITLE
Unable To Write Data To Serial Port Using Modbus Flex Write

### ISSUE THREAD

**Issue by nitinware** [biancode/node-red-contrib-modbus#111]
I have a digital board connected to My Raspberry PI by USB and the digit board accept input over RS485 Modbus RTU. I am using ModBus Flex Write to send the PLC command over serial port, but the command is not reaching to the device.

Below is the command which I want to send to the digital board connected over USB to raspberry pi.
<img width="741" alt="screen shot 2018-09-05 at 8 23 29 pm" src="https://user-images.githubusercontent.com/8107038/45129613-67aeb800-b14a-11e8-801d-8b07f7bc9a54.png">

I am also attaching the Node Red Flow JSON.

[Modbus_Write_json.txt](https://github.com/biancode/node-red-contrib-modbus/files/2355183/Modbus_Write_json.txt)

Any help is highly appreciated, Thanks.

**Comment by biancode** [comment]
I'm sorry, but please read the template for issues!

## Support/Advice
 - support/advice request => **Please do not submit support requests here**, instead use [the link to our support page](https://bianco-royal.cloud/supporter/#/content/backer), please!
