### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by iridiu** [biancode/node-red-contrib-modbus#112]
I'm using Node-Red contrib ModBus to read the registers from a power meter that is connected via RS485 to a serial to TCP bridge and to Node-Red running on a Raspberry Pi 3 compute module.

Majority of registers are read correctly, for example, for current intensity I can see values for L1 and L2 but without L3, for voltage and active power can display the values for L1, L2, L3 ... Other registers such as total active power, frequency etc returns a value [0, 65472] or NaN.

I replaced the power meter, also the ModBus bridge, I updated and reinstalled Node-Red, but reading the registers returns the same values. I used Modscan in this setup and I can display all the registers correctly.

Node-Red and contrib-modbus are updated and latest versions installed.
Here is a demo flow:

[{"id":"4938af43.b6975","type":"function","z":"1faa546d.dcd77c","name":"","func":"// Create new Buffer based on array bytes\nconst buf = Buffer.from(msg.payload.buffer).swap16();\n\n// Represent these bytes as Float32\nconst value = buf.readFloatLE(0).toFixed(2);\n\n// save the value\nmsg.payload = value;\nreturn msg;","outputs":1,"noerr":0,"x":350,"y":80,"wires":[["9113bce6.bab6c","74f43d06.f891f4","b10136ec.4beb68"]]},{"id":"9113bce6.bab6c","type":"ui_gauge","z":"1faa546d.dcd77c","name":"L1","group":"fbce3164.ebb78","order":0,"width":"2","height":"2","gtype":"compass","title":"L1","label":"A","format":"{{value | number:2 }}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":490,"y":60,"wires":[]},{"id":"c3177dab.69072","type":"function","z":"1faa546d.dcd77c","name":"","func":"// Create new Buffer based on array bytes\nconst buf = Buffer.from(msg.payload.buffer).swap16();\n\n// Represent these bytes as Float32\nconst value = buf.readFloatLE(4).toFixed(2);\n\n// save the value\nmsg.payload = value;\nreturn msg;","outputs":1,"noerr":0,"x":350,"y":160,"wires":[["fa027e26.53958","dcac4bc9.60d438","85e59618.734d08"]]},{"id":"751f4017.88405","type":"function","z":"1faa546d.dcd77c","name":"","func":"// Create new Buffer based on array bytes\nconst buf = Buffer.from(msg.payload.buffer);\n\n// Represent these bytes as Float32\nconst value = buf.readFloatBE(8).toFixed(2);\n\n// save the value\nmsg.payload = value;\nreturn msg;","outputs":1,"noerr":0,"x":350,"y":240,"wires":[["21ae7ef0.3b84f2","16e29f25.ef2db1","c3bdb396.9fbe1"]]},{"id":"fa027e26.53958","type":"ui_gauge","z":"1faa546d.dcd77c","name":"L2","group":"fbce3164.ebb78","order":0,"width":"2","height":"2","gtype":"compass","title":"L2","label":"A","format":"{{value | number:2 }}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":490,"y":140,"wires":[]},{"id":"21ae7ef0.3b84f2","type":"ui_gauge","z":"1faa546d.dcd77c","name":"L3","group":"fbce3164.ebb78","order":0,"width":"2","height":"2","gtype":"compass","title":"L3","label":"A","format":"{{value | number:2 }}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":490,"y":220,"wires":[]},{"id":"4cf3930e.1718cc","type":"modbus-read","z":"1faa546d.dcd77c","name":"I: phase current","topic":"","showStatusActivities":false,"logIOActivities":false,"showErrors":false,"unitid":"2","dataType":"HoldingRegister","adr":"3000","quantity":"6","rate":"1","rateUnit":"s","delayOnStart":false,"startDelayTime":"10","server":"820de6ae.87def8","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":180,"y":160,"wires":[[],["4938af43.b6975","c3177dab.69072","751f4017.88405"]]},{"id":"74f43d06.f891f4","type":"ui_text","z":"1faa546d.dcd77c","group":"d65d416.9ce20c","order":0,"width":0,"height":0,"name":"","label":"L1","format":"{{value | number:2 }}","layout":"row-spread","x":490,"y":100,"wires":[]},{"id":"dcac4bc9.60d438","type":"ui_text","z":"1faa546d.dcd77c","group":"d65d416.9ce20c","order":0,"width":0,"height":0,"name":"","label":"L2","format":"{{value | number:2 }}","layout":"row-spread","x":490,"y":180,"wires":[]},{"id":"16e29f25.ef2db1","type":"ui_text","z":"1faa546d.dcd77c","group":"d65d416.9ce20c","order":0,"width":0,"height":0,"name":"","label":"L3","format":"{{value | number:2 }}","layout":"row-spread","x":490,"y":260,"wires":[]},{"id":"b10136ec.4beb68","type":"change","z":"1faa546d.dcd77c","name":"Current L1","rules":[{"t":"set","p":"topic","pt":"msg","to":"L1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":630,"y":80,"wires":[["7078ba6f.d326a4"]]},{"id":"85e59618.734d08","type":"change","z":"1faa546d.dcd77c","name":"Current L2","rules":[{"t":"set","p":"topic","pt":"msg","to":"L2","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":630,"y":160,"wires":[["7078ba6f.d326a4"]]},{"id":"c3bdb396.9fbe1","type":"change","z":"1faa546d.dcd77c","name":"Current L3","rules":[{"t":"set","p":"topic","pt":"msg","to":"L3","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":630,"y":240,"wires":[["7078ba6f.d326a4"]]},{"id":"7078ba6f.d326a4","type":"ui_chart","z":"1faa546d.dcd77c","name":"","group":"d65d416.9ce20c","order":0,"width":0,"height":0,"label":"Phases current","chartType":"line","legend":"true","xformat":"HH:mm:ss","interpolate":"bezier","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"60","cutout":0,"useOneColor":false,"colors":["#800000","#000000","#c0c0c0","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":true,"x":880,"y":160,"wires":[[],[]]},{"id":"fbce3164.ebb78","type":"ui_group","z":"","name":"Current","tab":"8e5db1d7.c63a7","order":1,"disp":true,"width":"6","collapse":false},{"id":"820de6ae.87def8","type":"modbus-client","z":"","name":"iEM3355","clienttype":"tcp","bufferCommands":true,"stateLogEnabled":false,"tcpHost":"192.168.1.2","tcpPort":"502","tcpType":"DEFAULT","serialPort":"/dev/ttyUSB","serialType":"RTU-BUFFERD","serialBaudrate":"9600","serialDatabits":"8","serialStopbits":"1","serialParity":"none","serialConnectionDelay":"100","unit_id":2,"commandDelay":1,"clientTimeout":1000,"reconnectTimeout":2000},{"id":"d65d416.9ce20c","type":"ui_group","z":"","name":"Current","tab":"c4432af3.db3708","order":6,"disp":true,"width":"6","collapse":false},{"id":"8e5db1d7.c63a7","type":"ui_tab","z":"","name":"Power meter","icon":"power","order":8},{"id":"c4432af3.db3708","type":"ui_tab","z":"","name":"Control board","icon":"work","order":2}]

**Comment by biancode** [comment]
I'm sorry, but please read and fill out the template for your issues, please!
