### ISSUE TITLE
Node-Red Modbus Read node not working with Delta PLC 

### ISSUE THREAD

**Issue by rakesh5283** [biancode/node-red-contrib-modbus#113]
I am very new to Node-red,, I want to read the Delta DVP20EX2 serial PLC modbus RTU data to my laptop. But Node-red modbus library does not reading any data .. 

I have tried all the possible combinations on setting side. But its does help me out to get the data from delta PLC. 

Delta PLC sending data and working fine I have tested with Modbus Slave Application.. But with Node-Red its not working.. 

Any Help on NOde-Red library side will be very helpful. 

Thanks
Rakesh Patel

**Comment by biancode** [comment]
Dear Rakesh,

I'm sorry, but I need more information. Please, fill out the template for your issue and open a new issue. Add some logs and read the Wiki, please!
