### ISSUE TITLE
Modbus Server returns data from addresses offset if starting register greater than zero 

### ISSUE THREAD

**Issue by stevereids** [biancode/node-red-contrib-modbus#114]
**I'm submitting a ...** 
## Problem
 - (x) bug report

 **Current behavior**
 Modbus server returns data from incorrect register addresses if the requested data does not start at register index zero.
 
 **Expected behavior**
 Modbus server returns correct register data
 
 **Minimal reproduction of the problem with instructions**
   1. Start with empty flow, drop in single Modbus Server node and deploy
   2. Using Generic modbus client set first few registers with data (say equal to register address)
   3. Using Generic modbus client read back data using non zero offset and note misalignment of data to register address.

![2018-10-04 15_10_07-10 0 0 102 - remote desktop connection](https://user-images.githubusercontent.com/9821333/46479731-a25a4d80-c7e7-11e8-8a37-76375bc19fd5.png)
[node-red-contrib-modbus_server_error_testflow.txt](https://github.com/biancode/node-red-contrib-modbus/files/2446657/node-red-contrib-modbus_server_error_testflow.txt)
[node-red-contrib_modbus_server_error.zip](https://github.com/biancode/node-red-contrib-modbus/files/2446684/node-red-contrib_modbus_server_error.zip)

   
### Your Environment
**Please tell us about your environment:**

  * (x) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it  
  * Device :
    
    - ( ) macOS: v 
    - (x) Linux: v Ubuntu 16.04 LTS
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting Modbus system:
   
     - Name   :Modbus test client is ModScan32
     - Version: v4
     - Vendor : WinTech
     - Link   : http://www.win-tech.com
     
    
* **node-red-contrib-modbus version:** `v4.0`

* **Node:** (min. 6.x)
   `node --version` = v10.10.0

**Comment by stevereids** [comment]
Just rolled-back the version of node-red-contrib-modbus to v3.6.1 and problem disappears.
  
![2018-10-04 16_16_24-10 0 0 102 - remote desktop connection](https://user-images.githubusercontent.com/9821333/46484051-e0a83a80-c7f0-11e8-9c52-877edc1910ec.png)

**Comment by biancode** [comment]
Hi Steve,

could you test with the [library simple server](https://github.com/Cloud-Automation/node-modbus), please?

greetings,
Klaus

**Comment by biancode** [comment]
@stefanpoeter some known issue here?

**Comment by stefanpoeter** [comment]
@biancode what jsmodbus version are you using?

**Comment by biancode** [comment]
> @biancode what jsmodbus version are you using?

@stefanpoeter "jsmodbus": "3.0.0"

**Comment by stefanpoeter** [comment]
Yes, 3.0.0 has some issues, use a newer version.

**Comment by biancode** [comment]
@stevereids please test v4.0.1

**Comment by stevereids** [comment]
Hi Klaus,

I have just upgraded from 3.6.1 to 4.1.0 and everything looks good.  I need
to leave it running as I have had issues with memory leaks in earlier
versions.

Thanks.

Steve
