### ISSUE TITLE
Modbus Flex Connector does not change serial port

### ISSUE THREAD

**Issue by escaglia** [biancode/node-red-contrib-modbus#115]
**I'm submitting a bug report**
 
 **Current behavior**
Serial port is not changing when I try to change it through Modbus Flex Connector.
 
 **Expected behavior**
Serial port should change when I try to change it through Modbus Flex Connector.
 
 **Minimal reproduction of the problem with instructions**
Set serial port to '/dev/ttyUSB0' in modbus-client configuration, then inject msg.payload = {'connectorType': 'SERIAL', 'serialPort':'/dev/ttyUSB1'} to to Modbus Flex Connector node and look at modbus-client reconnecting message in debug panel, it should display the old serial port and not the new one!

### Your Environment

  * (x) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it
  
  * Device :
    
    - ( ) macOS: v 
    - (x) Linux: v 
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting Modbus system:
   
     - Name   : custom device
   
    
* **node-red-contrib-modbus version:** ``
v4.0.0 18d655e24a5cce6aa6456ce566cc559514705960

* **Node:** (min. 6.x)
   `node --version` = v8.12.0

**Comment by biancode** [comment]
Thank you and happy wiring with v4.0.1
