### ISSUE TITLE
Node noob wondering if this repo is available on v0.10.48

### ISSUE THREAD

**Issue by JoeyR** [biancode/node-red-contrib-modbus#117]
## Simple question to get some hint
 - (x) simple question => please visit the Wiki, the YouTube tutorials and the Info tab by clicking on the node inside Node-RED before

I'm new to node/nodered and was wondering if this node available/possible to port this to v0.10.48? I could also port my hardware to v8... but I am using a constrained armv5 chipset, so I'm trying to attack this problem from both sides. Thank you in advance!

**Comment by biancode** [comment]
If want to port the lib, you need to this for some of all dependencies too. You could test to port v1 [tgas](https://github.com/biancode/node-red-contrib-modbus/tags)
