### ISSUE TITLE
Modbus RTU slave/server?

### ISSUE THREAD

**Issue by thatcadguy** [biancode/node-red-contrib-modbus#127]
Hi, I just noticed that there's apparently no Modbus RTU server node -- and even more surprising, I can't even find a npm package with one. Any plans to add a Modbus RTU server node in the future?

**Comment by biancode** [comment]
Hi, I'm sorry there are no plans for now to add Modbus RTU server, because it was never missed in the last three years, but feel free to contribute and send your pull request for a RTU server!

**Comment by sensbo** [comment]
It seams to be that still nobody miss the option to simulate a MODBUS RTU Slave with node-red? Because this would be a nice use-case for this feature request: Simulated virtual MODBUS RTU Slave signals.
