### ISSUE TITLE
Used Defined Function Codes

### ISSUE THREAD

**Issue by apb2019** [biancode/node-red-contrib-modbus#129]
**I'm submitting a ...**  (check one with "x")

 - (X) simple question =>
Does "node-red-contrib-modbus" support User Defined Function Codes  (i.e FC 65 to 72 and from 100 to 110 decimal) or is it limited to the just the function codes implemented in Modbus-Serial

**Comment by biancode** [comment]
not from the frontend ask @yaacov if it possible in the actual version of the lib, please

**Comment by biancode** [comment]
reopen if it possible as a feature request
