### ISSUE TITLE
How to read float values ?

### ISSUE THREAD

**Issue by abhishekricky** [biancode/node-red-contrib-modbus#13]
Hi,

I m storing float values in holding register. How to read them in float as . Node is only providing values in decimal

**Comment by biancode** [comment]
It works similar to [endianness](https://github.com/biancode/node-red-contrib-modbus/wiki/Buffer-and-endianness---32Bit---64Bit) - use to response buffer to convert as many 16Bit chunks you need, and you know the best, how your float is correct to interpret.
