### ISSUE TITLE
which version can support on Node-RED 0.15.3 and node.js 0.10.x

### ISSUE THREAD

**Issue by hnhuangda** [biancode/node-red-contrib-modbus#130]
which version can support on Node-RED 0.15.3 and node.js 0.10.x

**Comment by biancode** [comment]
none - sorry ;)

**Comment by biancode** [comment]
you could try to compile and test, but there no official support for these versions

**Comment by biancode** [comment]
`npm install -g node-red-contrib-modbus --unsafe-perm --build-from-source`
