### ISSUE TITLE
Node-red broken

### ISSUE THREAD

**Issue by PierreScerri** [biancode/node-red-contrib-modbus#131]
**Current behavior**
Using Hassio Node-red add-on 1.3.2 all is well. 
Upgrading to 1.3.3 breaks node-red.
modbus 4.1.1 is using serialport 0.6.8.  Cannot update to 0.7.0

### Your Environment
**Please tell us about your environment:**
Hassio 0.88.1 on rpi 3. Node-red add-on 1.3.2
SDM120 and SDM230 connected via USB to the pi

**Comment by biancode** [comment]
please fill out the template for issues - I do not understand what is the problem an I do not know that versions - sorry
