### ISSUE TITLE
Modbus TCP Server trigger on write

### ISSUE THREAD

**Issue by obstler42** [biancode/node-red-contrib-modbus#132]
- (X) help wanted => you read all information and watched relevant YouTube tutorials, but you need more help

I have a modbus device (heating controller) that periodically pushes out new data to a Modbus TCP Server -- I set it up to connect to the node-red-contrib-modbus Server and that basically works fine. Now I would like to act upon data received by the node-red tcp-modbus server, By I can't seem to get it to do anything every time a new value is written.

I don't want to poll the server -- I want it to react immediately a new holding register value is written by the external modbus device.

Is there a way to get the server node to start pushing out msgs/flows upon every WRITE?

**Comment by biancode** [comment]
I would say you could do this with the Flex Server.

**Comment by CTGControls** [comment]
I would like to do something similar to [obstler42](https://github.com/obstler42) but I am not getting any output from the "Modbus-Flex Server" or the Modbus-Server when a successful right happens. I have a debug node on each of the 5 outputs.
![Untitled](https://github.com/BiancoRoyal/node-red-contrib-modbus/assets/15036058/1826a171-17fb-4eb9-8a85-35ead75bf484)
