### ISSUE TITLE
FSM Reset On State QUEUEING

### ISSUE THREAD

**Issue by PierreScerri** [biancode/node-red-contrib-modbus#133]
**I'm submitting a ...**  (check one with "x")

## Support/Advice
 - support/advice request => **Please do not submit support requests here**, instead use [the link to our support page](https://bianco-royal.cloud/supporter/#/content/backer), please!

## Feature
 - ( ) feature request
 
 **What is the motivation / use case for changing the behavior?**
 

## Simple question to get some hint
 - ( ) simple question => please visit the Wiki, the YouTube tutorials and the Info tab by clicking on the node inside Node-RED before
 - ( ) help wanted => you read all information and watched relevant YouTube tutorials, but you need more help

## Problem
 - ( ) bug report => please search github for a similar issue or PR and test Modbus problems with the [modbus-serial](https://github.com/yaacov/node-modbus-serial) package before submitting
 - (X) unexpected behavior => please visit the Wiki before
 
 **Current behavior**
 
 Frequent 'FSM Reset On State QUEUEING' message

 **Expected behavior**
 
 
 **Minimal reproduction of the problem with instructions**
 
   1. 
   2. 
   3. 
   
### Your Environment
**Please tell us about your environment:**

  * (X) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) package global from source (using git clone)
  * ( ) I have installed [modbus-serial](https://github.com/yaacov/node-modbus-serial) as a global package (using npm i -g)
  
  Yes, modbus-serial is the name but it does all, TCP and Serial.
  The node-modbus package is just for the Modbus Server node.  
  
  * Device :
    
    - ( ) macOS: v 
    - ( ) Linux: v 
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - (X) Other:
         - Name: HassOS
         - Version: 2.10
   
   * Description of the connecting Modbus system:
   
     - Name   : SDM120/SDM230 via RS485 to USB converter to Raspberry Pi3 B
     - Version:
     - Vendor :
     - Link   : https://
     
    
* **node-red-contrib-modbus version:** ``

4.1.3

* **Node:** (min. 6.x)
   `node --version` = 9.11.1

**Comment by biancode** [comment]
There should exist a problem in communication. The node is on queuing and gets a reset of the network or serial port. Maybe you are polling the device to fast? Check your flow to communicate less or more slowly.

**Comment by PierreScerri** [comment]
Polling is every 15 seconds.

**Comment by PierreScerri** [comment]
No errors with 30s.  Readjusted to 20s.  Seems to be working fine.

Thank you.

**Comment by biancode** [comment]
If you get that problem again let me review your flow to help, please.

**Comment by PierreScerri** [comment]
I have included my flow.

Every 1m32 (sometimes randomly 2m32) I get this error:  'TransactionTimedOutError: Timed out' immediately followed by: 'FSM Reset On State QUEUEING' for each modbus read node (ie 9 messages).

Then I get:
![Screen Shot 2019-03-28 at 15 56 30](https://user-images.githubusercontent.com/34303331/55167979-43600a80-5172-11e9-96b1-f9cf267b390b.png)
followed by  
![Screen Shot 2019-03-28 at 15 17 11](https://user-images.githubusercontent.com/34303331/55168003-4e1a9f80-5172-11e9-8b82-ce2433b70911.png)
and it restarts.

Also, whenever I deploy the flow it gets stuck on 'waiting' and I have to restart node-red.

Any suggestions would be most welcome

`[{"id":"df73e07d.dc5bb","type":"tab","label":"SDM","disabled":false,"info":""},{"id":"3c3eaa46.8311e6","type":"comment","z":"df73e07d.dc5bb","name":"SDM230 Energy Meter","info":"","x":160,"y":80,"wires":[]},{"id":"5444ad0a.946dc4","type":"modbus-read","z":"df73e07d.dc5bb","name":"SDM 230 Voltage","topic":"","showStatusActivities":true,"logIOActivities":false,"showErrors":true,"unitid":"1","dataType":"InputRegister","adr":"0","quantity":"2","rate":"20","rateUnit":"s","delayOnStart":false,"startDelayTime":"","server":"fe372aa0.f8c9d8","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":160,"y":140,"wires":[["478fd4f6.3a0b2c"],[]]},{"id":"478fd4f6.3a0b2c","type":"function","z":"df73e07d.dc5bb","name":"Voltage","func":"var rawData = new ArrayBuffer(4);\nvar intView = new Uint16Array(rawData);\nvar fltView = new Float32Array(rawData);\n\nintView[0] = msg.payload[1]; //low\nintView[1] = msg.payload[0]; //high\n\nmsg.payload = parseFloat(fltView[0].toFixed(0));\nmsg.topic = \"voltage\";\n\nnode.status({fill:\"blue\",shape:\"ring\",text:msg.topic + \":\" + msg.payload});    \n\nreturn msg;","outputs":1,"noerr":0,"x":380,"y":140,"wires":[["a2b9b965.1b5818","7eb54e40.eee44"]]},{"id":"96d56a4f.ed4b6","type":"modbus-read","z":"df73e07d.dc5bb","name":"SDM 230 Current","topic":"","showStatusActivities":true,"logIOActivities":false,"showErrors":true,"unitid":"1","dataType":"InputRegister","adr":"6","quantity":"2","rate":"20","rateUnit":"s","delayOnStart":false,"startDelayTime":"","server":"fe372aa0.f8c9d8","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":160,"y":200,"wires":[["6fd7a085.f4d9f"],[]]},{"id":"6fd7a085.f4d9f","type":"function","z":"df73e07d.dc5bb","name":"Current","func":"var rawData = new ArrayBuffer(4);\nvar intView = new Uint16Array(rawData);\nvar fltView = new Float32Array(rawData);\n\nintView[0] = msg.payload[1]; //low\nintView[1] = msg.payload[0]; //high\n\nmsg.payload = parseFloat(fltView[0].toFixed(1));\nmsg.topic = \"current\";\n\nnode.status({fill:\"blue\",shape:\"ring\",text:msg.topic + \":\" + msg.payload});    \n\nreturn msg;","outputs":1,"noerr":0,"x":380,"y":200,"wires":[["1164b3a0.98d95c","7eb54e40.eee44"]]},{"id":"5e6d7ebc.925c1","type":"modbus-read","z":"df73e07d.dc5bb","name":"SDM 230 Power","topic":"","showStatusActivities":true,"logIOActivities":false,"showErrors":true,"unitid":"1","dataType":"InputRegister","adr":"12","quantity":"2","rate":"20","rateUnit":"s","delayOnStart":false,"startDelayTime":"","server":"fe372aa0.f8c9d8","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":160,"y":260,"wires":[["bc76e392.d54248"],[]]},{"id":"bc76e392.d54248","type":"function","z":"df73e07d.dc5bb","name":"Power","func":"var rawData = new ArrayBuffer(4);\nvar intView = new Uint16Array(rawData);\nvar fltView = new Float32Array(rawData);\n\nintView[0] = msg.payload[1]; //low\nintView[1] = msg.payload[0]; //high\n\nmsg.payload = parseFloat(fltView[0].toFixed(1));\nmsg.topic = \"power\";\n\nnode.status({fill:\"blue\",shape:\"ring\",text:msg.topic + \":\" + msg.payload});    \n\nreturn msg;","outputs":1,"noerr":0,"x":370,"y":260,"wires":[["72babe22.f2369","7eb54e40.eee44","89f9ab77.79789"]]},{"id":"ec883c2d.3cc0a8","type":"modbus-read","z":"df73e07d.dc5bb","name":"SDM 230 Energy Imp","topic":"","showStatusActivities":true,"logIOActivities":false,"showErrors":true,"unitid":"1","dataType":"InputRegister","adr":"72","quantity":"2","rate":"20","rateUnit":"s","delayOnStart":false,"startDelayTime":"","server":"fe372aa0.f8c9d8","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":180,"y":320,"wires":[["629847da.5e933"],[]]},{"id":"629847da.5e933","type":"function","z":"df73e07d.dc5bb","name":"Import","func":"var rawData = new ArrayBuffer(4);\nvar intView = new Uint16Array(rawData);\nvar fltView = new Float32Array(rawData);\n\nintView[0] = msg.payload[1]; //low\nintView[1] = msg.payload[0]; //high\n\nmsg.payload = (parseFloat(fltView[0]) * 1.00195 + 36481.26).toFixed(2) ;\nmsg.topic = \"import\";\n\nnode.status({fill:\"blue\",shape:\"ring\",text:msg.topic + \":\" + msg.payload});    \n\nreturn msg;","outputs":1,"noerr":0,"x":370,"y":320,"wires":[["5ea597c8.757f4","7eb54e40.eee44"]]},{"id":"b35fa8cf.93ce38","type":"modbus-read","z":"df73e07d.dc5bb","name":"SDM 230 Energy Exp","topic":"","showStatusActivities":true,"logIOActivities":false,"showErrors":true,"unitid":"1","dataType":"InputRegister","adr":"74","quantity":"2","rate":"20","rateUnit":"s","delayOnStart":false,"startDelayTime":"","server":"fe372aa0.f8c9d8","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":180,"y":380,"wires":[["681bf682.e9f2b"],[]]},{"id":"681bf682.e9f2b","type":"function","z":"df73e07d.dc5bb","name":"Export","func":"var rawData = new ArrayBuffer(4);\nvar intView = new Uint16Array(rawData);\nvar fltView = new Float32Array(rawData);\n\nintView[0] = msg.payload[1]; //low\nintView[1] = msg.payload[0]; //high\n\nmsg.payload = (parseFloat(fltView[0]) * 1.00238 + 10274.41).toFixed(2);\nmsg.topic = \"export\";\n\nnode.status({fill:\"blue\",shape:\"ring\",text:msg.topic + \":\" + msg.payload});    \n\nreturn msg;","outputs":1,"noerr":0,"x":370,"y":380,"wires":[["e9dae86b.285c68","7eb54e40.eee44"]]},{"id":"cd71e18d.08937","type":"comment","z":"df73e07d.dc5bb","name":"SDM120 Energy Meter","info":"","x":160,"y":460,"wires":[]},{"id":"748dc192.84fc4","type":"modbus-read","z":"df73e07d.dc5bb","name":"SDM 120 Voltage","topic":"","showStatusActivities":true,"logIOActivities":false,"showErrors":true,"unitid":"2","dataType":"InputRegister","adr":"0","quantity":"2","rate":"20","rateUnit":"s","delayOnStart":false,"startDelayTime":"","server":"fe372aa0.f8c9d8","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":160,"y":520,"wires":[["53bc2b78.7c1344"],[]]},{"id":"53bc2b78.7c1344","type":"function","z":"df73e07d.dc5bb","name":"Voltage","func":"var rawData = new ArrayBuffer(4);\nvar intView = new Uint16Array(rawData);\nvar fltView = new Float32Array(rawData);\n\nintView[0] = msg.payload[1]; //low\nintView[1] = msg.payload[0]; //high\n\nmsg.payload = parseFloat(fltView[0].toFixed(0));\nmsg.topic = \"voltage\";\n\nnode.status({fill:\"blue\",shape:\"ring\",text:msg.topic + \":\" + msg.payload});    \n\nreturn msg;","outputs":1,"noerr":0,"x":380,"y":520,"wires":[["c59c902f.a1f1d8","d827052f.6e85a8"]]},{"id":"3f182dd1.b53982","type":"modbus-read","z":"df73e07d.dc5bb","name":"SDM 120 Current","topic":"","showStatusActivities":true,"logIOActivities":false,"showErrors":true,"unitid":"2","dataType":"InputRegister","adr":"6","quantity":"2","rate":"20","rateUnit":"s","delayOnStart":false,"startDelayTime":"","server":"fe372aa0.f8c9d8","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":160,"y":580,"wires":[["9000ab81.228ca"],[]]},{"id":"9000ab81.228ca","type":"function","z":"df73e07d.dc5bb","name":"Current","func":"var rawData = new ArrayBuffer(4);\nvar intView = new Uint16Array(rawData);\nvar fltView = new Float32Array(rawData);\n\nintView[0] = msg.payload[1]; //low\nintView[1] = msg.payload[0]; //high\n\nmsg.payload = parseFloat(fltView[0].toFixed(1));\nmsg.topic = \"current\";\n\nnode.status({fill:\"blue\",shape:\"ring\",text:msg.topic + \":\" + msg.payload});    \n\nreturn msg;","outputs":1,"noerr":0,"x":380,"y":580,"wires":[["7b7ce764.c62658","d827052f.6e85a8"]]},{"id":"88f176b1.543d5","type":"modbus-read","z":"df73e07d.dc5bb","name":"SDM 120 Power","topic":"","showStatusActivities":true,"logIOActivities":false,"showErrors":true,"unitid":"2","dataType":"InputRegister","adr":"12","quantity":"2","rate":"20","rateUnit":"s","delayOnStart":false,"startDelayTime":"","server":"fe372aa0.f8c9d8","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":160,"y":640,"wires":[["7725b723.a0a688"],[]]},{"id":"7725b723.a0a688","type":"function","z":"df73e07d.dc5bb","name":"Power","func":"var rawData = new ArrayBuffer(4);\nvar intView = new Uint16Array(rawData);\nvar fltView = new Float32Array(rawData);\n\nintView[0] = msg.payload[1]; //low\nintView[1] = msg.payload[0]; //high\n\nmsg.payload = parseFloat(fltView[0].toFixed(1));\nmsg.topic = \"power\";\n\nnode.status({fill:\"blue\",shape:\"ring\",text:msg.topic + \":\" + msg.payload});    \n\nreturn msg;","outputs":1,"noerr":0,"x":370,"y":640,"wires":[["a70aabf8.6b229","d827052f.6e85a8","36652685.ae25b2"]]},{"id":"dd362076.4ed13","type":"modbus-read","z":"df73e07d.dc5bb","name":"SDM 120 Energy Sol","topic":"","showStatusActivities":true,"logIOActivities":false,"showErrors":true,"unitid":"2","dataType":"InputRegister","adr":"72","quantity":"2","rate":"20","rateUnit":"s","delayOnStart":false,"startDelayTime":"","server":"fe372aa0.f8c9d8","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":170,"y":700,"wires":[["6fad733b.fec91c"],[]]},{"id":"6fad733b.fec91c","type":"function","z":"df73e07d.dc5bb","name":"Solar","func":"var rawData = new ArrayBuffer(4);\nvar intView = new Uint16Array(rawData);\nvar fltView = new Float32Array(rawData);\n\nintView[0] = msg.payload[1]; //low\nintView[1] = msg.payload[0]; //high\n\nmsg.payload = parseFloat(fltView[0] * 1.00069 + 21326.51).toFixed(2);\nmsg.topic = \"solar\";\n\nnode.status({fill:\"blue\",shape:\"ring\",text:msg.topic + \":\" + msg.payload});    \n\nreturn msg;","outputs":1,"noerr":0,"x":370,"y":700,"wires":[["cccc164b.72cf","d827052f.6e85a8"]]},{"id":"d827052f.6e85a8","type":"function","z":"df73e07d.dc5bb","name":"Build object","func":"watch_topic = \"solar\";\nvar output = {};\n\ncontext.set(msg.topic,msg.payload);\n\nif (context.get(\"voltage\")!==undefined) {\n    output.voltage = context.get(\"voltage\");\n}\nif (context.get(\"current\")!==undefined) {\n    output.current = context.get(\"current\");\n}\nif (context.get(\"power\")!==undefined) {\n    output.power = context.get(\"power\");\n}\nif (context.get(\"solar\")!==undefined) {\n    output.solar = context.get(\"solar\");\n}\nmsg.payload = output;\n\nif (msg.topic===watch_topic) {\n    msg.topic = \"sdm120\";\n    return msg;\n}","outputs":1,"noerr":0,"x":730,"y":600,"wires":[["fd970da8.fe4198"]]},{"id":"fd970da8.fe4198","type":"mqtt out","z":"df73e07d.dc5bb","name":"SDM120","topic":"sdm120","qos":"","retain":"","broker":"c28a2dad.22663","x":900,"y":600,"wires":[]},{"id":"7eb54e40.eee44","type":"function","z":"df73e07d.dc5bb","name":"Build object","func":"watch_topic = \"export\";\nvar output = {};\n\ncontext.set(msg.topic,msg.payload);\n\nif (context.get(\"voltage\")!==undefined) {\n    output.voltage = context.get(\"voltage\");\n}\nif (context.get(\"current\")!==undefined) {\n    output.current = context.get(\"current\");\n}\nif (context.get(\"power\")!==undefined) {\n    output.power = context.get(\"power\");\n}\nif (context.get(\"import\")!==undefined) {\n    output.import = context.get(\"import\");\n}\nif (context.get(\"export\")!==undefined) {\n    output.export = context.get(\"export\");\n}\nmsg.payload = output;\n\nif (msg.topic===watch_topic) {\n    msg.topic = \"sdm230\";\n    return msg;\n}","outputs":1,"noerr":0,"x":730,"y":280,"wires":[["950e7299.b2de58"]]},{"id":"950e7299.b2de58","type":"mqtt out","z":"df73e07d.dc5bb","name":"SDM230","topic":"sdm230","qos":"","retain":"","broker":"c28a2dad.22663","x":900,"y":280,"wires":[]},{"id":"a2b9b965.1b5818","type":"ui_text","z":"df73e07d.dc5bb","group":"213dd143.0f2136","order":1,"width":0,"height":0,"name":"","label":"Voltage","format":"{{msg.payload}} V","layout":"row-spread","x":540,"y":140,"wires":[]},{"id":"1164b3a0.98d95c","type":"ui_text","z":"df73e07d.dc5bb","group":"213dd143.0f2136","order":2,"width":0,"height":0,"name":"","label":"Current","format":"{{msg.payload}} A","layout":"row-spread","x":540,"y":200,"wires":[]},{"id":"72babe22.f2369","type":"ui_text","z":"df73e07d.dc5bb","group":"213dd143.0f2136","order":3,"width":0,"height":0,"name":"","label":"Power","format":"{{msg.payload}} W","layout":"row-spread","x":530,"y":260,"wires":[]},{"id":"5ea597c8.757f4","type":"ui_text","z":"df73e07d.dc5bb","group":"213dd143.0f2136","order":4,"width":0,"height":0,"name":"","label":"Energy Import","format":"{{msg.payload}} kWh","layout":"row-spread","x":560,"y":320,"wires":[]},{"id":"e9dae86b.285c68","type":"ui_text","z":"df73e07d.dc5bb","group":"213dd143.0f2136","order":5,"width":0,"height":0,"name":"","label":"Energy Export","format":"{{msg.payload}} kWh","layout":"row-spread","x":560,"y":380,"wires":[]},{"id":"c59c902f.a1f1d8","type":"ui_text","z":"df73e07d.dc5bb","group":"5a3ddb88.1e6714","order":1,"width":0,"height":0,"name":"","label":"Voltage","format":"{{msg.payload}} V","layout":"row-spread","x":540,"y":520,"wires":[]},{"id":"a70aabf8.6b229","type":"ui_text","z":"df73e07d.dc5bb","group":"5a3ddb88.1e6714","order":3,"width":0,"height":0,"name":"","label":"Power","format":"{{msg.payload}} W","layout":"row-spread","x":530,"y":640,"wires":[]},{"id":"cccc164b.72cf","type":"ui_text","z":"df73e07d.dc5bb","group":"5a3ddb88.1e6714","order":4,"width":0,"height":0,"name":"","label":"Energy Solar","format":"{{msg.payload}} kWh","layout":"row-spread","x":550,"y":700,"wires":[]},{"id":"7b7ce764.c62658","type":"ui_text","z":"df73e07d.dc5bb","group":"5a3ddb88.1e6714","order":2,"width":0,"height":0,"name":"","label":"Current","format":"{{msg.payload}} A","layout":"row-spread","x":540,"y":580,"wires":[]},{"id":"36652685.ae25b2","type":"ui_chart","z":"df73e07d.dc5bb","name":"","group":"d6595a1d.63d978","order":2,"width":"0","height":"0","label":"Solar","chartType":"line","legend":"false","xformat":"dd HH:mm","interpolate":"bezier","nodata":"Acquiring Data","dot":false,"ymin":"0","ymax":"3000","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"86400","cutout":0,"useOneColor":false,"colors":["#2CA02C","#AEC7E8","#FF7F0E","#1F77B4","#98DF8A","#D62728","#FF9896","#9467BD","#C5B0D5"],"useOldStyle":false,"outputs":1,"x":530,"y":760,"wires":[[]]},{"id":"89f9ab77.79789","type":"ui_chart","z":"df73e07d.dc5bb","name":"","group":"d6595a1d.63d978","order":1,"width":"0","height":"0","label":"Grid","chartType":"line","legend":"false","xformat":"dd HH:mm","interpolate":"bezier","nodata":"Acquiring Data","dot":false,"ymin":"-3000","ymax":"9000","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"86400","cutout":0,"useOneColor":false,"colors":["#1F77B4","#AEC7E8","#FF7F0E","#2CA02C","#98DF8A","#D62728","#FF9896","#9467BD","#C5B0D5"],"useOldStyle":false,"outputs":1,"x":530,"y":440,"wires":[[]]},{"id":"fe372aa0.f8c9d8","type":"modbus-client","z":"","name":"Serial_9600_8_N_1","clienttype":"serial","bufferCommands":true,"stateLogEnabled":false,"tcpHost":"127.0.0.1","tcpPort":"502","tcpType":"DEFAULT","serialPort":"/dev/ttyUSB0","serialType":"RTU-BUFFERD","serialBaudrate":"9600","serialDatabits":"8","serialStopbits":"1","serialParity":"none","serialConnectionDelay":"100","unit_id":"","commandDelay":30,"clientTimeout":2000,"reconnectTimeout":5000},{"id":"c28a2dad.22663","type":"mqtt-broker","z":"","name":"","broker":"192.168.1.200","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthRetain":"false","birthPayload":"","closeTopic":"","closeQos":"0","closeRetain":"false","closePayload":"","willTopic":"","willQos":"0","willRetain":"false","willPayload":""},{"id":"213dd143.0f2136","type":"ui_group","z":"","name":"SDM230","tab":"db77dc69.ae668","order":1,"disp":true,"width":"6","collapse":false},{"id":"5a3ddb88.1e6714","type":"ui_group","z":"","name":"SDM120","tab":"db77dc69.ae668","order":2,"disp":true,"width":"6","collapse":false},{"id":"d6595a1d.63d978","type":"ui_group","z":"","name":"Graphs","tab":"db77dc69.ae668","order":3,"disp":true,"width":"6","collapse":false},{"id":"db77dc69.ae668","type":"ui_tab","z":"","name":"Modbus","icon":"dashboard","order":1,"disabled":false,"hidden":false}]`

**Comment by biancode** [comment]
it is not the time in requesting - it is the queue delay of just 30ms - try to set 100 ms or more in the connector

**Comment by biancode** [comment]
you could request every 2 seconds by 200 ms queue delay  ( 200ms * 5values = 1000ms - serial request of 5 needs 1 sec.) - or - request poll per 1 sec by 120 ms ( 120 ms * 5 = 600ms) ... and so on - you are requesting 5 serial commands per poll if you insert more nodes think about your time to handle all request between node-red and your device ;)

**Comment by PierreScerri** [comment]
Ok I think I've got it.  
I have 9 read nodes. 
So setting queue delay of 200ms gives 1800ms.  

If I set polling to 3s it should be fine.
Correct me if I'm wrong.

Thank you for your help

**Comment by marcu5au** [comment]
Hi! I came here with the same issue "FSM Reset On State QUEUEING" and after reading the above have set my Queue Delay to 200ms to solve most of my issue.
I pole my SDM230 every 30 seconds (reading five registers) and I'm using the USR-W610 (RS485 to WiFi converter). 
I actually suspect the root cause is the USR-W610 as it is terrible with handling the TCP stack over WiFi compared to the older (now discontinued) USR-WIFI232-604 unit.
Thanks for the comments above to help me out!
