### ISSUE TITLE
TypeError: Converting circular structure to JSON when connecting to "http in" node

### ISSUE THREAD

**Issue by coolchip** [biancode/node-red-contrib-modbus#14]
First, thank you very much for this great node!

I have one tiny problem. When I connect your Modbus Flex Write direct or in line to an "http in" node, I get the Error above.
This is because of the msg.req and/or the msg.res generated by the "http in" node. I don't know the code of your node, but perhaps you can parse only the msg.payload part.

**Comment by biancode** [comment]
use a function node to send data just, if you have it like:

if(msg.res) {
  buildTheRightPayloadYouNeed()
}

if(msg.req) {
  enhanceTheRightPayloadYouNeed()
}

**Comment by coolchip** [comment]
Yes, I can do so. I also found a work around for this. But at it's a little bit tricky to found that error.
I think this is the problem (modbus-write.js):

```
      if (node.showStatusActivities) {
        setNodeStatusTo(modbusClient.statlyMachine.getMachineState())
        verboseLog(**JSON.toString(msg)**)
      }
```

**Comment by biancode** [comment]
oh yes, that should be:

`verboseLog(JSON.stringify(msg))`

**Comment by biancode** [comment]
please test with node-red-contrib-modbus@1.0.6
