### ISSUE TITLE
Update config nodes by incoming payload

### ISSUE THREAD

**Issue by WeeSee** [biancode/node-red-contrib-modbus#142]
I need to modify/add config nodes for the Modbus Getter node externall triggered by a web request 

    /add-modbus-device?ip=1.2.3.4&port=502 

Since modbus device communication data is stored in config nodes this is not possible today.
 
It would be perfect if the config data could be updated/overridden by the incoming payload of the  Modbus Getter node.

* Is such a feature on the roadmap?
* Should I create a pull request for this repo?
* Or is this a bad idea - why?

**Comment by biancode** [comment]
test the flex connector with your incoming  HTTP event ... is that what you want?

**Comment by biancode** [comment]
reopen if you need more
