### ISSUE TITLE
PLC address access

### ISSUE THREAD

**Issue by Argental2019** [biancode/node-red-contrib-modbus#152]
I'm submitting a question:
I have installed Node-RED with Modbus-Package in order to connect via TCP to a Kinco PLC. 
The provider has sent a documentation to access to every specific PCL variable. 

I set up the Node Server and it connects to the master properly, but the Node Read doesn't get any data at all. 

Unfortunatelly, I am not skilled at Modbus protocol, and I have no response from the provider, so I state the question here: 

The document describes the following addesses location: 

Variable     Gateway     Bit
A               401000        0
B               401000        1 
C               401000        2
.
.
X               401002        0
Y               401002        1
Z               401002        2

The question is: what values should I assign into the Node textboxes? 
-FC
-Address
-Quantity

in order to get data from any of these variables? 
Thanks so much in advance

( ) help wanted

( ) I am using just the Node-RED package and got [modbus-serial](https://github.com/yaacov/node-modbus-serial) package installed with it
 Yes, modbus-serial is the name but it does all, TCP and Serial.
 The node-modbus package is just for the Modbus Server node.  
  
 Device :  
( ) Raspbian: 3

   * Description of the connecting Modbus system:
   
     - Name   : Kinco
     - Version: x
     - Vendor : x
   
   

Node:
   `node --version` = lastest

**Comment by biancode** [comment]
That is not an issue - please, try to find some help in the slack channel of Node-RED
