### ISSUE TITLE
When a Modbus RTU request times out no further Modbus RTU requests are sent

### ISSUE THREAD

**Issue by SuperJojo2001** [biancode/node-red-contrib-modbus#18]
The js "modbus-client-core.js" sets the state machine to state 'error' in case a request times out. This is ok so far. 
On Modbus TCP the onSocketConnect() functions sets it back to state 'ready' due to autoconnect.
On Modbus RTU there is no auto connect, so state machine remains in state 'error'. As consequence all new incoming input requests will fail to flush due to this check:

if (this.inState('ready')) {
     flush();
}

**Comment by biancode** [comment]
A test device would be great. If Hilscher can send one to me, then I can test with it.
