### ISSUE TITLE
New connection Modbus RTU over TCP

### ISSUE THREAD

**Issue by nokautai** [biancode/node-red-contrib-modbus#19]
Hello. Great Job. But can You implement Modbus RTU over TCP connection - standard serial Modbus RTU queries/answers thru TCP/IP channel? I have RS485 to Ethernet gateway which can't convert Modbus TCP quries to Modbus RTU format, only waiting connection as RS485 TCP server and allows transparent flow.

http://www.simplymodbus.ca/TCP.htm
https://github.com/stephane/libmodbus/issues/192

**Comment by biancode** [comment]
did you try the TCP RTU?

![screenshot 2017-03-21 at 03 25 29 pm](https://cloud.githubusercontent.com/assets/4369867/24152009/a5c36c70-0e4a-11e7-8591-3ae81c3464cd.png)

**Comment by nokautai** [comment]
I can't see RTU and RTU-BUFFERED in TCP list, only TELNET and C701. Node version 1.0.8.
![node-red-modbus](https://cloud.githubusercontent.com/assets/26570717/24159562/0eaf62da-0e68-11e7-8955-f08c58368969.jpg)

**Comment by biancode** [comment]
you can see the more with `npm info` and package name
Please, try node-red-contrib-modbus@1.0.9-alpha - with my gateway it works a bit but not at all.
I'm working on it.

**Comment by nokautai** [comment]
Thank you very much! On TCP->RTU-BUFFERED not respond, but combination TCP->TELNET gets response from MODBUS device.
![001](https://cloud.githubusercontent.com/assets/26570717/24170780/a4d7f4d0-0e8a-11e7-9e54-40fea374475f.png)
![002](https://cloud.githubusercontent.com/assets/26570717/24170781/a4d9fcda-0e8a-11e7-8422-fd9d43142961.png)

**Comment by M0DDer** [comment]
Version node-red-contrib-modbus 5.23.1
ModBus over RTU still works ONLY with "Telnet" selected
p,s. in my moxa converter RTU is selected  (not telnet. telnet also avaliable here)
