### ISSUE TITLE
All modbus nodes should only debug if RED.settings.verbose

### ISSUE THREAD

**Issue by Hugobox** [biancode/node-red-contrib-modbus#20]
Hi!
Could all the modbus nodes act like the modbus-server and only print warnings in debug if NR is set to verbose?

I believe it would simply involve replacing in each node:
node.warn(failureMsg)
with:
if (RED.settings.verbose) {
	node.warn(failureMsg)
}

Let me know what you think!

**Comment by biancode** [comment]
Hi,

Do you use v1.0.8?

**Comment by Hugobox** [comment]
Yes!

**Comment by biancode** [comment]
may that could be a request on node-red itself ;)

**Comment by biancode** [comment]
you can set your node-red log level to error

**Comment by Hugobox** [comment]
Its not the console logging that's problematic, its the debug panel in the editor. As I work on my dev machine which is not connected to all the modbus devices, the debug panel gets filled with modbus warnings and it gets harder to troubleshoot other parts of the flow. I'd like a way to let those nodes know that I know they aren't connected to the real system and RED.settings.verbose seems like a great solution, don't you agree?

**Comment by biancode** [comment]
No, I do not agree in that case, but I'll give a new 'Show Errors' option to handle this.

**Comment by Hugobox** [comment]
That would totally work! Thanks for your time!

**Comment by biancode** [comment]
please try node-red-contrib-modbus@1.0.9-beta

**Comment by Hugobox** [comment]
Thanks! Totally working for me!
