### ISSUE TITLE
Request for Modbus Flex Writer

### ISSUE THREAD

**Issue by mcdonaldajr** [biancode/node-red-contrib-modbus#22]
Modbus Flex Getter is an excellent function for building more data driven nodes. Could we have a Modbus Flex Writer function too? One that can use the message from Flex Getter to set the type, address and quantity?

**Comment by biancode** [comment]
see v0.9.0 - have fun and let me know your testing results, please!

**Comment by mcdonaldajr** [comment]
Tested successfully. Thanks Again. Managed to create a reusable subnode using this.
