### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by ankumara** [biancode/node-red-contrib-modbus#22]
there is error msg:

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v11-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@0.10.29 (node-v11 ABI) (falling back to source compile with node-gyp)

the link is broken

thanks

**Comment by biancode** [comment]
Your node.js is to old - use the wiki articles, please.

**Comment by ankumara** [comment]
Ow, ic. now i remember, last time running the upgrade command (from wiki) i got error. 

thanks
