### ISSUE TITLE
modbus-flex-getter does not appear to read address 0

### ISSUE THREAD

**Issue by mcdonaldajr** [biancode/node-red-contrib-modbus#23]
I can use modbus-read to read holding register 0, but modbus-flex-getter shows undefined when I try to read address 0.

**Comment by biancode** [comment]
there it is - should be fixed in next release 0.9.+

**Comment by biancode** [comment]
![screenshot 2016-11-27 at 06 19 08 pm](https://cloud.githubusercontent.com/assets/4369867/20650064/09d01a5a-b4ce-11e6-81fa-241284e20fc0.png)

**Comment by mcdonaldajr** [comment]
Tested successfully. Many Thanks.
