### ISSUE TITLE
[modbus-serial] Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by zixzixzix** [biancode/node-red-contrib-modbus#24]
[warn] [modbus-serial] Error: Could not locate the bindings file. Tried:
 → /Users/zix/.node-red/node_modules/serialport/build/serialport.node
 → /Users/zix/.node-red/node_modules/serialport/build/Debug/serialport.node
 → /Users/zix/.node-red/node_modules/serialport/build/Release/serialport.node
 → /Users/zix/.node-red/node_modules/serialport/out/Debug/serialport.node
 → /Users/zix/.node-red/node_modules/serialport/Debug/serialport.node
 → /Users/zix/.node-red/node_modules/serialport/out/Release/serialport.node
 → /Users/zix/.node-red/node_modules/serialport/Release/serialport.node
 → /Users/zix/.node-red/node_modules/serialport/build/default/serialport.node
 → /Users/zix/.node-red/node_modules/serialport/compiled/6.10.2/darwin/x64/serialport.node

**Comment by biancode** [comment]
That is a serialport problem - sorry - please try to find the solution in their FAQ.

or try

```
$ sudo npm install -g node-gyp
$ cd node_modules/serialport
$ node-gyp rebuild
```

That could also be a permission problem.
