### ISSUE TITLE
Cannot install on RPi 3 Raspbian up to date

### ISSUE THREAD

**Issue by AndriusWild** [biancode/node-red-contrib-modbus#28]
Hello,
I keep installing node-red-contrib-modbus but the module does not show up in node-red.

Here is the output of the terminal:

pi@raspberrypi:~ $ npm install node-red-contrib-modbus
npm WARN engine node-red-contrib-modbus@1.0.11: wanted: {"node":">=6.9"} (current: {"node":"0.10.29","npm":"2.15.12"})
npm WARN engine node-modbus@3.2.6: wanted: {"node":">=4.7.0"} (current: {"node":"0.10.29","npm":"2.15.12"})
-
> serialport@4.0.7 install /home/pi/node_modules/node-red-contrib-modbus/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v11-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@0.10.29 (node-v11 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/pi/node_modules/node-red-contrib-modbus/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/obj.target/serialport.node
  COPY Release/serialport.node
make: Leaving directory '/home/pi/node_modules/node-red-contrib-modbus/node_modules/serialport/build'
node-red-contrib-modbus@1.0.11 node_modules/node-red-contrib-modbus
├── stately.js@1.3.0
├── debug@2.6.3 (ms@0.7.2)
├── modbus-serial@5.2.9
├── node-modbus@3.2.6 (net@1.0.2, stampit-log@0.3.0, stampit-state-machine@0.2.1, stampit-event-bus@0.1.1, crc@3.4.4, bluebird@3.5.0)
├── stampit@2.1.2 (supermixer@1.0.3, lodash@3.10.1)
└── serialport@4.0.7 (bindings@1.2.1, commander@2.9.0, lie@3.1.1, object.assign@4.0.4, nan@2.6.2)

I did try adding --unsafe-perm to the command but it did not help.
raspberry pi 3 with raspbian jessie up to date

Any ideas?

**Comment by biancode** [comment]
Please, watch the Wiki Pages ;)
