### ISSUE TITLE
Incorrect error handling in `set_modbus_error`

### ISSUE THREAD

**Issue by nallenscott** [biancode/node-red-contrib-modbus#28]
Catch nodes are not being triggered when an error occurs during a read/write. I think this is because the original `msg` is not included in the call to node.error(). See the node-red docs on [error handling](https://nodered.org/docs/writing-functions#handling-errors). As a test, I edited [this line](https://github.com/biancode/node-red-contrib-modbus/blob/master/src/modbus-flex-getter.js#L264) in `modbus-flex-getter.js` for each of the switch cases:

```js
}).fail( function (err) { set_modbus_error(err, msg); });
```
... and edited [`set_modbus_error`](https://github.com/biancode/node-red-contrib-modbus/blob/master/src/modbus-flex-getter.js#L354-L361) to include the original `msg` object:

```js
function set_modbus_error(err, msg) {
    if (err) {
        set_node_status_to("error");
        node.error('Modbus Flex Getter client: ' + JSON.stringify(err), msg);
        return false;
    }
    return true;
}
```

... and now catch nodes are working as expected :)

**Comment by biancode** [comment]
API docs (http://nodered.org/docs/creating-nodes/node-js) says:

this.log("Something happened");
this.warn("Something happened you should know about");
this.error("Oh no, something bad happened");

**Comment by biancode** [comment]
OK

**Comment by biancode** [comment]
comming soon with v0.10.x

**Comment by nallenscott** [comment]
Why was this closed? Was it fixed?

**Comment by biancode** [comment]
comming soon with v0.10.x - you can give it a try with the tag @0.10.5 on npm install

**Comment by nallenscott** [comment]
Got it. Thanks!

**Comment by biancode** [comment]
please try @0.11.2 with whole new serial engine
