### ISSUE TITLE
modbus-write and modbus-flex-write not working in 0.10.7

### ISSUE THREAD

**Issue by cfatfc** [biancode/node-red-contrib-modbus#29]
FC16 works in 0.9.5, but not in 0.10.7. In 0.10.7, the node connects to the remote Modbus-TCP device, but there is no output when the flow is triggered.

**Comment by biancode** [comment]
please try npm install node-red-contrib-modbus@0.11.4

**Comment by biancode** [comment]
please try npm install node-red-contrib-modbus@0.11.5

**Comment by biancode** [comment]
there is a whole new modbus communication and queueing in v0.11.x to get more control from the nodes in node-red - may you need more than one connection to your gateway, if the workload is to high - when all nodes sending together every second for example - or you have to find the right queue command delay for your device

**Comment by biancode** [comment]
![screenshot 2016-12-31 at 01 36 56 pm](https://cloud.githubusercontent.com/assets/4369867/21577531/3918456c-cf5e-11e6-8a27-568092376d9e.png)
