### ISSUE TITLE
FC6 not working in modbus-write

### ISSUE THREAD

**Issue by cfatfc** [biancode/node-red-contrib-modbus#30]
version 0.9.5 modbus-write node returns the following error:

Modbus Write client: {"errorCode":134,"exceptionCode":11,"message":"GATEWAY TARGET DEVICE FAILED TO RESPOND"}

Can successfully write to a single holding register in version 0.9.5 with FC16.

**Comment by biancode** [comment]
please try npm install node-red-contrib-modbus@0.11.4

**Comment by biancode** [comment]
please try npm install node-red-contrib-modbus@0.11.5

**Comment by biancode** [comment]
in the new version 0.11.7 you have to try setup Queue commands with true and play with the queue command delay time
![screenshot 2016-12-31 at 01 24 33 pm](https://cloud.githubusercontent.com/assets/4369867/21577481/8304ea56-cf5c-11e6-9eed-e5b74087eb58.png)

**Comment by biancode** [comment]
My testing flow with unbufferd and buffered VServer ( PLC Sim on Windows ) and some hardware (Schneider PLC TCP and Renu Panel Modbus Serial)

![screenshot 2016-12-31 at 01 26 26 pm](https://cloud.githubusercontent.com/assets/4369867/21577487/c28813ba-cf5c-11e6-8b52-12f7791c1c03.png)

![screenshot 2016-12-31 at 01 27 28 pm](https://cloud.githubusercontent.com/assets/4369867/21577493/e5f1ac3a-cf5c-11e6-88ce-eed0ad144a23.png)

**Comment by biancode** [comment]
Serial Modbus Panel
![screenshot 2016-12-31 at 01 29 54 pm](https://cloud.githubusercontent.com/assets/4369867/21577498/3f22884c-cf5d-11e6-9223-9ed6c0c81b83.png)
