### ISSUE TITLE
FC16 issue

### ISSUE THREAD

**Issue by creativeng** [biancode/node-red-contrib-modbus#34]
Hi 
i need to use FC16 to write a single register (vendor requirement), but it seems that if I assign quantity to 1 it get an error message  saying that : 

Quantity should be less or equal to register payload array length: undefined addr 181 Q: 1

and im writing to test with inject node just "1"

same if i try to use qty 2...

**Comment by biancode** [comment]
Set your input to JSON array [value] 

[1234]  input have to be array on fc 16

**Comment by creativeng** [comment]
ok thanks, it works fine...
M
