### ISSUE TITLE
Dynamic configuration of the slave IP address

### ISSUE THREAD

**Issue by lcvcl** [biancode/node-red-contrib-modbus#39]
Just as flex-getter can use msg to configure address, why not allow the slave's ip address to be configured using msg?
In the actual production, some companies do cloud platform convergence equipment need to set the ip from the station to read the information, but these IP is not necessarily static, the company may change the slave IP or add a new from Station, if it is written in HTML config, each time you need to change the configuration once again ip address, this is a very troublesome thing. But if the node can read information from the file, and then use its IP and other information for dynamic configuration of this is quite comfortable, then why not let IP address can be dynamically configured?
There is a problem in your project to see the existence of the client, but ask what is not the actual node?

**Comment by biancode** [comment]
> There is a problem in your project to see the existence of the client, but ask what is not the actual node?

No, this is how it works in Node-RED. It is not a problem.

**Comment by lcvcl** [comment]
i don'think is a problem
i think if the ip can config dynamic ,it will be better

**Comment by lcvcl** [comment]
two question 
1 why the client not dispaly
2 if the ip config dynamic ,will more adapt in the actual enviroment

**Comment by biancode** [comment]
If you want a dynamically TCP connection, then it has to be a very new node to handle connection on Modbus.

1) this is Node-RED
2) think about multiple requests, just to have the IP dynamically is not the end

**Comment by biancode** [comment]
if you want to discuss that contact me or let's have an online session

**Comment by biancode** [comment]
watch [YouTube](https://youtu.be/TO88NryAT_c) for configuration

**Comment by biancode** [comment]
try v1.2.0
