### ISSUE TITLE
just a little extension to the modbus server node

### ISSUE THREAD

**Issue by jwende** [biancode/node-red-contrib-modbus#4]
to dump the content of the memory I extended modbus-server.js with:

        node.on("input", function (msg) {
            verbose_log('Input:' + msg);
			var msg1 = node.server.getHolding();
			var msg2 = node.server.getCoils();
			var msg3 = node.server.getInput();
			node.send(build_message(msg1,msg2,msg3));
        });
and added three output terminals to the html file.
This gives me the option to send a message to the input terminal and dump the the memory to debug or send it as MQTT message.
Cheers
Joerg

**Comment by biancode** [comment]
see v0.6.2
