### ISSUE TITLE
Need to get ASCII or string values from modbus registers

### ISSUE THREAD

**Issue by Kartheek1512** [biancode/node-red-contrib-modbus#40]
I am using modbus flex getter node and I get "int" values from the registers.  Is there a way to get the values in ascii or string format?
As of now, I get 
a[0]=21328 
In binary, it is 0101001101010000  which represents "S" in string/ASCII

I want to get a[0]=S

**Comment by biancode** [comment]
use the Buffer and you will have all what you need

**Comment by biancode** [comment]
that is the reason why the output sends the Buffer to - see [JS Buffer tutorial](https://www.tutorialspoint.com/nodejs/nodejs_buffers.htm)
