### ISSUE TITLE
Polling by TCP

### ISSUE THREAD

**Issue by icarogregorio** [biancode/node-red-contrib-modbus#48]
Hi friends!

Actually we can made a modbus polling by the MB Flex Getter node with unitid parametter!
But I need to made a polling system with a Modbus TCP! How we can made this system to poll the IP Address ? If this tool is not deployed yet! Consider this issue as a suggestion.

Thank you very much!

**Comment by biancode** [comment]
duplicate see [Issue 41](https://github.com/biancode/node-red-contrib-modbus/issues/41)
