### ISSUE TITLE
Error when starting Node-red

### ISSUE THREAD

**Issue by icarogregorio** [biancode/node-red-contrib-modbus#49]
When I start Node-red the error bellow is appeared:

29 Jun 18:36:17 - [error] [modbus-server:cdfeeaa8.22a2f8] TypeError: Buffer.alloc is not a function

**Comment by biancode** [comment]
You need Node.js >=4.7 - see the [Wiki](https://github.com/biancode/node-red-contrib-modbus/wiki/Raspberry-PI) - I'll add that in the package.json file.
