### ISSUE TITLE
Modbus server node triggering

### ISSUE THREAD

**Issue by rvdm82** [biancode/node-red-contrib-modbus#55]
Hi

I'm using a PLC to send certain data to modbus-server when the PLC inputs/outputs change. To get the data out of the modbus-server node, I need to inject something in the node every second to get the state of the outputs. Is there a way to trigger the outputs automatically when a Modbus TCP message arrives ? Is polling the only option ?

**Comment by biancode** [comment]
Please, read the [Website of Modbus](http://modbus.org/) to find out what Modbus is and what you can do with.
