### ISSUE TITLE
Reading modbus data which is in 32 bit sint format 

### ISSUE THREAD

**Issue by Kartheek1512** [biancode/node-red-contrib-modbus#60]
Hi klaus, 

  I have been struggling since past few days to read data from a Power meter. Data sheet link below. Its registers are in 32 bit signed. 
http://www.elkor.net/pdfs/WattsOn-Mark_II_Manual.pdf

 When the actual value that i have to see is -273 in registers 257 ad 278. But instead i see values 62717 and 65535. can you please help me. Now a days many industrial power meters are saving values in 32 bits. 
![image](https://user-images.githubusercontent.com/9099868/31748295-0eebcf9e-b427-11e7-83bb-b702f0753504.png)

**Comment by biancode** [comment]
see [Wiki](https://github.com/biancode/node-red-contrib-modbus/wiki/Buffer-8Bit,-16Bit,-32Bit,-64Bit,-128Bit-...-reading-with-SDM630-power-meter)

**Comment by biancode** [comment]
feel free to [support](https://bianco-royal.cloud/supporter/) us for our help

**Comment by Kartheek1512** [comment]
Thanks Klaus.. The link helped me.

I have another device which does DNP3 communication. Do you have an idea
how to get data from those devices. I believe there is no node for DNP3 in
node-red.
