### ISSUE TITLE
Catching timeouts

### ISSUE THREAD

**Issue by mascapollo** [biancode/node-red-contrib-modbus#64]
Hello There, 

It is possible to catch read or write timeouts from the flex nodes?

**Comment by biancode** [comment]
Hi,

please, switch on the option "Show Errors" and "Show Activities" and insert a catch node with debug msg.

Happy testing!
Klaus

**Comment by biancode** [comment]
`[{"id":"89631453.62a938","type":"catch","z":"f5ce9336.3dec9","name":"","scope":null,"x":530,"y":70,"wires":[["a80c480b.97e4b8"]]},{"id":"a80c480b.97e4b8","type":"debug","z":"f5ce9336.3dec9","name":"","active":true,"console":"false","complete":"true","x":680,"y":70,"wires":[]}]`

**Comment by mascapollo** [comment]
Hello Klaus.

I have this setup but the catch node does no send any timeout message. 

![image](https://user-images.githubusercontent.com/28955853/32358813-62b74e7e-c01f-11e7-98a0-0e5ef56d0eaa.png)
