### ISSUE TITLE
QUESTION: Modbus TX Enable Shield

### ISSUE THREAD

**Issue by candronikos** [biancode/node-red-contrib-modbus#67]
Hi Klaus , really appreciate your assistance so far :)

For our application it's a requirement for the TX Enable toggled correctly. Is it possible to set a GPIO pin to use with Raspberry PI RS485 shields that use a GPIO pin?

**Comment by biancode** [comment]
keywords could be ttyma0 or pi uart

**Comment by candronikos** [comment]
Not sure what you mean here. Should I add them to the title?

**Comment by biancode** [comment]
keywords could be ttyama0 or pi uart to search for

**Comment by biancode** [comment]
You want to connect serial RS485 via GPIO on RPi, right?

**Comment by candronikos** [comment]
If we need to bit bang on GPIO pins to make this work then I'm ok with it. Whatever works best.

We were using a UART to rs485 shield but found that the TX enable is tied to the TX pin. My colleague wants a proper shield to use and also drivers that will support it.

**Comment by biancode** [comment]
OK, but I have never worked with the GPIO for serial or TX. I use [USB sticks](http://usb-rs485.eu/) with RS485 or RS232.

**Comment by biancode** [comment]
Please, reopen if there is more or let me know about your experiences if it works well for you ;)

**Comment by candronikos** [comment]
Right, yes I was using USB converters to loop back the serial for testing. Unfortunately, it's a requirement that we do not use these in the field. I will definitely keep an eye on this project :)
