### ISSUE TITLE
Input an array of values to read

### ISSUE THREAD

**Issue by robertsLando** [biancode/node-red-contrib-modbus#68]
Lot times I have to do multiple reads of modbus, to do this I need to create an array of inputs to send to a `modbus-flex getter`  and use a flow var as counter and a repeated inject that increments the counter and sends a `array[counter]` value to read. This is an example of the array of values to read:

```
var array = [ {"fc": 3, "unitid": 1, "address": 50 , "quantity": 10},
              {"fc": 1, "unitid": 1, "address": 1 , "quantity": 5},
              {"fc": 1, "unitid": 1, "address": 30 , "quantity": 10}      
            ];
```

My question is: is it possible to add a feature to mobus-flex-getter to accept an array like this as input and starts to read this values in cyclic with a delay between them (set throught node options?). I think this would be a very useful feature.

In this case also a tick option like _"Retry if read fails"_ would be great (retry to read a value if it fails)

**Comment by biancode** [comment]
For me, that is not a function of my nodes. You can build that with Node-RED nodes very easy. Sorry.
