### ISSUE TITLE
Catching timeouts in Serial RTU

### ISSUE THREAD

**Issue by candronikos** [biancode/node-red-contrib-modbus#70]
Hi Klaus,

It appears you were able to do this in the video linked [here](https://www.youtube.com/watch?v=8KFT9FQhp28) but I was unable to reproduce it. I assume you print the timeout errors using the `catch all` node and connecting it to a debug node?

I wish to used this to implement retry functionality in the event of a timeout. The way it's done now is by using a dictionary to keep track of the responses and comparing the msg_ids to the ones in the original message. It's a bit messy and using native error handling seems like a better idea.

**Comment by biancode** [comment]
You are right you have to use the status node for now.
