### ISSUE TITLE
Modscan like UI in node-red-dashboard

### ISSUE THREAD

**Issue by robertsLando** [biancode/node-red-contrib-modbus#72]
I have used node-red-contrib-modbus to create an UI (using node-red-dashboard) like Modscan software. You can check it out here: https://flows.nodered.org/flow/bc19aff2598d6a214bbfbe0e6f66ee64 

Enjoy  :smile:

**Comment by biancode** [comment]
honored with a [tweet](https://twitter.com/KlausLandsdorf/status/935559575373320192)
