### ISSUE TITLE
Relationship between "node-red-node-serialport" and "node-red-contrib-modbus"

### ISSUE THREAD

**Issue by kangskii** [biancode/node-red-contrib-modbus#73]
Hello,
I found on https://www.npmjs.com/package/node-red-contrib-modbus that node-red-node-serialport is one dependency library of node-red-contrib-modbus.

Q1: Does it mean node-red-contrib-modbus internally invoke the two nodes： serial in and serial out in node-red-node-serialport ?

To my understanding, if the node-red-contrib-modbus is used, we don't need to drag the node-red-node-serialport nodes into the modbus flow.

Q2: Actually, I now had some issues in using serial out node in node-red-node-serialport. If I now use some nodes in node-red-contrib-modbus, will I have the SAME problem ?

Thanks.

**Comment by biancode** [comment]
Hi,

I'm sorry, node-red-node-serialport is not a dependency it is a separate package from another developer. My package uses modbus-serial too if you mean that in your Q1. Do you mean that library? 

If your question is, how you could use serial from my package, then the answer is: Just select Serial or Serial Expert in the config node (connection client). Default selection is TCP.


![grafik](https://user-images.githubusercontent.com/4369867/33398457-4e2ac0f4-d54f-11e7-8a9a-18d3301b1e48.png)

![grafik](https://user-images.githubusercontent.com/4369867/33398470-5a4bf57e-d54f-11e7-819e-eee0903c0358.png)

![grafik](https://user-images.githubusercontent.com/4369867/33398479-62f3ba4a-d54f-11e7-8189-5a58bb8dfc62.png)

Does it help?

Happy wiring!
Klaus

**Comment by kangskii** [comment]
Hi， 
Thanks for your reply. 
There are 8 dependencies for your package: bson, debug, modbus-serial, node-modbus, serialport, stampit, stately.js, vm2. To make your package run on Node-RED, do I have to install them additionally ?

**Comment by biancode** [comment]
Hi,

The dependencies are managed by npm install. There is nothing to install additionally, but read the Github Wiki and NPM information about npm install.

To get more about the nodes and what they can do for your flow, please hover over in the list or drag and drop them to the flow window and watch the info tab at the right. 

Watch my YouTube videos and you will learn how it could work for you. 😉

Happy learning!
Klaus _

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by biancode** [comment]
Search YouTube for my package name to find...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kangskii** [comment]
Hi,
Thanks for you quick response.
I had limited access to youtube.

In the node-red-contrib-modbus library, there is no modbus client. And I find it in the Manage Palette, see attached figure, but the Modbus client is a dashed box.

Could you please give some suggestions if I want to develop a modbus client in node-red-contrib-modbus ?

![screenshot](https://user-images.githubusercontent.com/26109740/33422628-2dbc9592-d56b-11e7-8244-dc115d20d1a6.png)

**Comment by biancode** [comment]
Hi Eric,

Please, use the Node-RED documentation on their website first and learn how to work with that tool. There are many courses and tutorials about Node-RED. ;)

The modbus-client node is hidden by Node-RED, because it is a configuration node. As I said, please teach yourself about that basics of Node-RED. You could also contact the community via Slack in the Node-RED channel.

Happy learning!
Klaus

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kangskii** [comment]
Hi Klaus,

Well received. Thank you so much.

With regards,

Eric 

> 在 2017年11月30日，19:34，Klaus Landsdorf <notifications@github.com> 写道：
> 
> Klaus
