### ISSUE TITLE
High memory usage in modbus-getter

### ISSUE THREAD

**Issue by milosjovac** [biancode/node-red-contrib-modbus#75]
Hi Klaus,

I have a problem with memory consumption of the modbus-getter on the raspberry pi 3. Memory continuously piles up till ENOMEM error starts to popup. It behaves the same on 2 environments:

Linux 4.9.59-v7+ arm LE
Node-RED version: v0.17.5
Node.js  version: v8.9.3
node-redpcontrib-modbus version: v2.4.1

Linux 4.9.59-v7+ arm LE
Node-RED version: v0.17.4
Node.js  version: v4.8.2
node-redpcontrib-modbus version: v2.3.2

![image](https://user-images.githubusercontent.com/2808506/34158193-ba6a110a-e4c4-11e7-99ef-5cd92c710dfe.png)

Real flow logic is a bit more complex but leaking problem is reproducible with a [flow from the image.](https://gist.github.com/milosjovac/ba02adf79c851d7fd9c661531f4778ff)

**Comment by milosjovac** [comment]
Ok, I have a new hint about the problem

![image](https://user-images.githubusercontent.com/2808506/34167731-d8b23c50-e4e2-11e7-8743-b0467553254b.png)

**Comment by milosjovac** [comment]
Ok, I think I found the problem. [In this line](https://github.com/biancode/node-red-contrib-modbus/blob/fa51fa895855d2a634beca791c63e40050ad49fd/src/modbus-getter.js#L77) You set new message with messageId, but this is is always different (incremental), and I do not see elsewhere in code that you call node.bufferMessageList.delete() or bufferMessageList.clear()

![image](https://user-images.githubusercontent.com/2808506/34168679-7251227a-e4e5-11e7-920b-3f46fd62ffe4.png)

**Comment by milosjovac** [comment]
Or [you do](https://github.com/biancode/node-red-contrib-modbus/blob/fa51fa895855d2a634beca791c63e40050ad49fd/src/core/modbus-core.js#L22). Hmm..

**Comment by biancode** [comment]
it asnyc in 
`    function buildMessage (values, response, msg) {
      let origMsg = mbCore.getOriginalMessage(node.bufferMessageList, msg) || msg`

**Comment by biancode** [comment]
maybe you have a problem with Map.delete in your node version?

**Comment by biancode** [comment]
messages are deleted on success and error

**Comment by milosjovac** [comment]
Yes, I see. I will have to check. It behaves the same on 2 node versions btw. Will let you know about the results.

**Comment by milosjovac** [comment]
[origMsg](https://github.com/biancode/node-red-contrib-modbus/blob/fa51fa895855d2a634beca791c63e40050ad49fd/src/core/modbus-core.js#L22) has no property in payload called messageId

So map is always deleted with undefined.

You should just omit .paylod. in between and it should work. 

![image](https://user-images.githubusercontent.com/2808506/34169308-3defd60a-e4e7-11e7-8e07-888e4de3b512.png)

**Comment by biancode** [comment]
Yes, I see.

**Comment by biancode** [comment]
Please, test with v2.5.0

**Comment by milosjovac** [comment]
Tested. Memory footprint is now OK 👍
