### ISSUE TITLE
Modbus Flex Connector throws an error "o.set_node_status_properties is not a function"

### ISSUE THREAD

**Issue by MonkeyDo** [biancode/node-red-contrib-modbus#77]
Hello!

When using the flex connector, I get TypeErrors thrown by this line:
https://github.com/biancode/node-red-contrib-modbus/blob/fe322c5c950a363c6cfbc2768c241cd243abf6e2/src/modbus-flex-connector.js#L108

I had a look at the modbus-basics.js file and it looks like there is a function named `setNodeStatusProperties` in camel case, rather than hyphened.
https://github.com/biancode/node-red-contrib-modbus/blob/fe322c5c950a363c6cfbc2768c241cd243abf6e2/src/modbus-basics.js#L70

I suppose one of the two files is wrong, unless I misunderstood something…

Thanks for your help !

**Comment by biancode** [comment]
Oh yes, `setNodeStatusProperties` is the right one - Thank you!

**Comment by biancode** [comment]
v3.0.3 done by hotfix
