### ISSUE TITLE
Modbus RTU read with no result

### ISSUE THREAD

**Issue by rjbaat** [biancode/node-red-contrib-modbus#79]
Hi, 
I had node-red-contrib-modbus working on an embeddedpi on the ttyAMA0 port. It is still sending the reading correct, but not receiving the results anymore. Insted i get a timeout.

I have connected the wires to a usb to rs485 converter to a windows laptop running Simply Modbus slave software.

**What works:**
When i use 2x the rs485 converters.
1 rs485 usb converter connected to an rpi3 <--> 1 rs485 usb converter connected to a windows laptop. Then when i do a read FC3 unit 1 from 0-2 it does read the registers and get positive return. The slave software is showing the right conditions also.

**What doesn't work:**
When i use the ttyAMA0 port on the embeddedpi <--> rs485 usb converter on a windows laptop. 
The slave software is showing me the right read parameters that i send (FC3 unit 1 from 0-2). It is showing that it is returning data aswell. But it looks like the data never arrives on the embeddedpi. 

31.01.18 11:59:53 (+0100)   modbus-serial { action: 'send serial rtu buffered',
31.01.18 11:59:53 (+0100)   modbus-serial   data: <Buffer 01 03 00 00 00 02 c4 0b>,
31.01.18 11:59:53 (+0100)   modbus-serial   unitid: 1,
31.01.18 11:59:53 (+0100)   modbus-serial   functionCode: 3 } +34s
31.01.18 11:59:54 (+0100)   modbus-serial modbusErrorHandling:Timed out +34s

Is there something i can do to make it work again? 

In the attachment i have added a screen of the slave software. 

![slave](https://user-images.githubusercontent.com/2822419/35614159-697df1f0-066e-11e8-9643-6eb1ec39a61e.JPG)

**Comment by biancode** [comment]
Hi,

Please, I need to know all versions:

* nodejs
* node-red
* node-red-contrib-modbus

**Comment by biancode** [comment]
What was the version before as it worked?

**Comment by rjbaat** [comment]
I have tested the box with mbpoll aswell. But it has the same problem. Then i tested with a plain serial connection from box to box and box to windows. The result are:

box -> windows (message received = OK)
box <- windows (message NOT received)
box -> box (message received = OK)
box <- box (message received = OKE)

It seems that its a problem with the rs485 to usb converters. Since the RX lights on the box doesn't light up on the RX end. Only on the TX. When i get new converters i will try again.
