### ISSUE TITLE
TCP connection is not closing properly on redeploy

### ISSUE THREAD

**Issue by KaAnorr** [biancode/node-red-contrib-modbus#83]
Hi,
I'm currently using a raspberry pi as a slave with a PLC but the TCP connection is not closing properly on each redeploy so I have to reboot my plc each time.
Is there a close function to add to correct this problem?

**Comment by biancode** [comment]
Hi, the Modbus client calls the close function on every close - maybe it is an issue of the modbus-serial libary. Please, test with the examples from [modbus-serial](https://github.com/yaacov/node-modbus-serial/tree/master/examples), what happens on a close!

**Comment by biancode** [comment]
v3.3.1 has an update for modbus-serial too, please test it

**Comment by biancode** [comment]
reopen if you need more, please
