### ISSUE TITLE
Flex Server Request

### ISSUE THREAD

**Issue by behi88** [biancode/node-red-contrib-modbus#85]
I tested modbus tcp so many times, it is a very robust component
but it could really use dynamic server change in read and write.
let's say I have more the 10 Modbus TCP slave. I configure the servers at start up with Modbus flex connector I need to add one Modbus flex getter for each server to read their data.
sure I could just use 1 Flex connector and change the server every time I want to connect, but it takes time and do not work with big Modbus networks and also some slaves could not handle the TCP disconnect very well and stay connected for a long time and the second request from the same master become a new connection to them and eventually they overflow.
in Modbus RTU it is different: you have only 1 bus specification (baud rate , stop bit ,...) and the slaves distinguished by their Slave ID , so you don't need multi getter to connect to slaves
anyway it would be REALLY practical if you could add a server name (or IP) to flex getter and writer parameters
this way we could have 1 getter for all servers.

Thanks again.

**Comment by biancode** [comment]
As you wrote it takes time to connect via TCP and it is to much work for now. I'm sorry.
