### ISSUE TITLE
Sharing serial port

### ISSUE THREAD

**Issue by candronikos** [biancode/node-red-contrib-modbus#87]
My colleague has the following question any assistance would be appreciated:
The overarching goal is to create a TCP to RTU btrdge

---

Hi,

We’re using your Modbus RTU drivers through Node Red. They take control of the serial port as they need it for Modbus RTU request and response.
 
We have another application written in Python which needs to use the same serial port. The issue is the Node Red Modbus RTU drivers take control of the serial port and keep control of it, thus our other application can’t use it.
 
Is there any way your drivers can relinquish the serial port, once they complete their Modbus RTU request and response? Of course your drivers also need to retake control the next time they send a Modbus packet.
 
The idea is for each application (the Modbus RTU through Node Red and our other application), to take control of the serial port, use it, then relinquish it. That’s what we want.
 
Please advise how this can be done

**Comment by biancode** [comment]
... possible, but too much work for now and just one request in more than two years - I'm sorry.
