### ISSUE TITLE
Cannot catch TIME OUT error

### ISSUE THREAD

**Issue by kevin100702** [biancode/node-red-contrib-modbus#92]
I want to use the catch node to catch error messages, but I cannot catch TIME OUT error messages.

`[{"id":"6ded389b.82d758","type":"modbus-read","z":"7fbe9cc1.249f34","name":"","topic":"","showStatusActivities":true,"showErrors":true,"unitid":"1","dataType":"HoldingRegister","adr":"10","quantity":"2","rate":"1","rateUnit":"s","delayOnStart":false,"startDelayTime":"","server":"dbaf90.e019707","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":170,"y":240,"wires":[["b3454bdc.928538"],["66d63199.d3f43"]]},{"id":"b3454bdc.928538","type":"debug","z":"7fbe9cc1.249f34","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":380,"y":300,"wires":[]},{"id":"a79fd38a.56e42","type":"catch","z":"7fbe9cc1.249f34","name":"","scope":null,"x":180,"y":480,"wires":[["c159e5d.3556a18"]]},{"id":"c159e5d.3556a18","type":"debug","z":"7fbe9cc1.249f34","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":400,"y":460,"wires":[]},{"id":"66d63199.d3f43","type":"debug","z":"7fbe9cc1.249f34","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":380,"y":360,"wires":[]},{"id":"c729045a.ffe2d8","type":"modbus-flex-write","z":"7fbe9cc1.249f34","name":"","showStatusActivities":true,"showErrors":true,"server":"dbaf90.e019707","x":420,"y":120,"wires":[[],[]]},{"id":"b9d87aba.f72e58","type":"inject","z":"7fbe9cc1.249f34","name":"","topic":"","payload":"{\"value\": true,\"fc\": 5,\"unitid\": 1,\"address\": 11125,\"quantity\": 1}","payloadType":"json","repeat":"1","crontab":"","once":false,"onceDelay":0.1,"x":90,"y":100,"wires":[["c729045a.ffe2d8"]]},{"id":"40d6f7e8.7a2768","type":"modbus-queue-info","z":"7fbe9cc1.249f34","name":"","topic":"","unitid":"","lowLowLevel":25,"lowLevel":75,"highLevel":150,"highHighLevel":300,"server":"dbaf90.e019707","errorOnHighLevel":false,"x":520,"y":220,"wires":[["a354ec6f.078d5"]]},{"id":"a354ec6f.078d5","type":"debug","z":"7fbe9cc1.249f34","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":700,"y":240,"wires":[]},{"id":"dbaf90.e019707","type":"modbus-client","z":"","name":"","clienttype":"tcp","bufferCommands":true,"stateLogEnabled":true,"tcpHost":"127.0.0.1","tcpPort":"502","tcpType":"DEFAULT","serialPort":"/dev/ttyUSB","serialType":"RTU-BUFFERD","serialBaudrate":"9600","serialDatabits":"8","serialStopbits":"1","serialParity":"none","serialConnectionDelay":"100","unit_id":"1","commandDelay":"1","clientTimeout":"1000","reconnectTimeout":"2000"}]`

**Comment by biancode** [comment]
Hi, yes these error was declared as none error raising information over time. What do you want to do with that error? You can get it by the status node.

**Comment by biancode** [comment]
![grafik](https://user-images.githubusercontent.com/4369867/39410041-ad62fda2-4bf1-11e8-8c08-9427459230b9.png)

**Comment by biancode** [comment]
reopen if you need more, please

**Comment by kevin100702** [comment]
Thanks. I solved my problem with the status node. I want to use the time out error to re-execute my command.
