### ISSUE TITLE
FSM State On Reset INIT

### ISSUE THREAD

**Issue by biancode** [biancode/node-red-contrib-modbus#93]
from @apanasara  

Please help to resolve error msg 'FSM State On Reset INIT'
https://user-images.githubusercontent.com/902578/38973172-f4dc8ab4-43c1-11e8-9207-6bbd4e5a00dc.jpg

**Comment by biancode** [comment]
Hi, I need your [log from the console](https://github.com/biancode/node-red-contrib-modbus/wiki/DEBUG), please. What is the response from the device?

**Comment by biancode** [comment]
What about the Modbus error code? I am sorry, but I need more details and information.

**Comment by apanasara** [comment]
No error code... Written Only  'FSM State On Reset INIT'

**Comment by biancode** [comment]
'FSM State On Reset INIT' is normaly if the connection settings are wrong

**Comment by tinktonk** [comment]
We have the exact problem, usually working but it looks like we have some problem with the serial connection. If we reset the serialport it starts working again. We are running node-red on raspberry. 
Everytime we deploy we need to reset.

**Comment by biancode** [comment]
Please, try to give some delay in time for the device to connect if you are using the inject node.

<img width="471" alt="grafik" src="https://user-images.githubusercontent.com/4369867/40372813-c78f1430-5de5-11e8-96ef-1ddf94d39ddc.png">

**Comment by biancode** [comment]
<img width="532" alt="grafik" src="https://user-images.githubusercontent.com/4369867/40373332-f6dfd9ee-5de6-11e8-93dc-4e2071e8d22b.png">

... that is from the Modbus Read node

**Comment by biancode** [comment]
reopen or open some new if you got more to analyze
