### ISSUE TITLE
help my usb to rs232 timeout

### ISSUE THREAD

**Issue by jackymanbo** [biancode/node-red-contrib-modbus#94]
this init ..... 
![image](https://user-images.githubusercontent.com/16853755/39958874-b42b0202-563b-11e8-8b32-baeb3ce4dcd9.png)

start then
![image](https://user-images.githubusercontent.com/16853755/39958882-ee7144d0-563b-11e8-81f7-6d1cb159febe.png)

sorry my English isn't good

**Comment by biancode** [comment]
Hi, it looks like multiple answering without a end character to finish.

**Comment by biancode** [comment]
10,13 should be in the answer as you set in the sending message` \n\r`

**Comment by biancode** [comment]
Reopen if you need more ...
