### ISSUE TITLE
serial stop bits

### ISSUE THREAD

**Issue by Ghuru42** [biancode/node-red-contrib-modbus#96]
The device I'm trying to talk has a fixed port settings of 9600 8N2.
When trying to talk to this device with node-red-contrib-modbus the answear is not read all the way.
I have a second RS485 dongle on the line so I can sniff the line and see what happens.
Node-red sends a correct query, and the device responds with a correct respons.
But in node-red I get an error saying that is only receive 1 or 2 bytes of the complete message.

I have tried exporting the flow, changing the stop bits, and then reimport the flow.
I have also tried stopping node-red, editing the flow json file manually to set stopbits and then start node-red, but still no luck.

Any suggestion if this can be fixed?

**Comment by biancode** [comment]
<img width="532" alt="grafik" src="https://user-images.githubusercontent.com/4369867/40386403-efd22fd0-5e09-11e8-8ffc-61cb15493235.png">

Hi, and your settings are?
